version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://localhost:9200 || exit 1
      interval: 10s
      retries: 10
      start_period: 20s

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    command: ["serve"]
    healthcheck:
      test: curl -s http://localhost:11434/api/tags || exit 1
      interval: 10s
      retries: 10
      start_period: 20s

  rass-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rass_engine
    ports:
      - "8000:8000"
    depends_on:
      opensearch:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_INDEX_NAME=medical-docs
      - TOP_K=3
      - MAX_CHAT_HISTORY=10
      - MAX_FILES_PER_PATIENT=5
    restart: unless-stopped
