name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest coverage

      - name: Run Flake8 (Linting)
        run: |
          flake8 --max-line-length=100 --ignore=E203,E266,E501,W503 .

    #   - name: Check formatting with Black
    #     run: |
    #       black --check --diff .

    #   - name: Check imports with isort
    #     run: |
    #       isort --check-only --diff .

      - name: Run tests with Coverage
        run: |
          coverage run -m pytest tests/
          coverage xml
          coverage report -m

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
